services:
  frontend:
    image: joelgonzalezjimenez/frontend
    env_file: ".env1"
    ports:
      - "8080:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != charizard

  backend:
    image: joelgonzalezjimenez/backend
    env_file: ".env2"
    ports:
      - "8081:5000"
    networks:
      - back-tier
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != charizard

  mongodb:
    image: joelgonzalezjimenez/mongo:4.0
    volumes:
      - /mnt/shared_data:/data/db
    ports:
      - "8082:27017"
    networks:
      - back-tier
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == charmander

networks:
  back-tier: {}
