services:
  frontend:
    image: joelgonzalezjimenez/frontend
    env_file: ".env"
    ports:
      - "8080:3000"

  backend:
    image: joelgonzalezjimenez/backend
    env_file: ".env"
    ports:
      - "8081:5000"
    networks:
      - back-tier

  mongodb:
    image: joelgonzalezjimenez/mongo:4.0
#    volumes:
#      - db-data:/etc/data
    ports:
      - "8082:27017"
    networks:
      - back-tier

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"

networks:

  back-tier: {}